x = input()

x = x.replace('i','ki')
x = x.replace('k','ki')
x = x.replace('a','ka')
x = x.replace('b','bi')
x = x.replace('c','ci')
x = x.replace('d','di')
x = x.replace('e','ke')
x = x.replace('f','fi')
x = x.replace('g','gi')
x = x.replace('h','hi')
x = x.replace('j','ji')
x = x.replace('l','li')
x = x.replace('m','mi')
x = x.replace('n','ni')
x = x.replace('o','ko')
x = x.replace('p','pi')
x = x.replace('q','qi')
x = x.replace('r','ri')
x = x.replace('s','si')
x = x.replace('t','ti')
x = x.replace('u','ku')
x = x.replace('v','vi')
x = x.replace('w','wi')
x = x.replace('x','xi')
x = x.replace('y','ky')
x = x.replace('z','zi')
x = x.replace('ii', 'i')

print(x)
